#!/bin/bash
set -e -u -E
printf "$0: "
trap 'echo error at line $LINENO' ERR

repo=test.sodrepo
[[ -f $repo ]] && rm $repo
unset ${!__sod_*}

./sodrepo $repo create > /dev/null
./sodrepo $repo add intel 16.0.2 1 x86_64 "summary" --provides='compiler' <<____

  =  EMAIL  user@host 
# comment
@ /x/y/z
+	PATH	@/bin
  
# another comment
=        XYZ	/lib:@/lib64

____

function addpkg() {
    ./sodrepo $repo add "$@" x86_64 '' <<<''
}
addpkg intel 13.1.1 1 --provides='compiler'
addpkg intel 14.0.4 1 --provides='compiler'
addpkg intel 15.0.2 1 --provides='compiler'
addpkg intel 15.0.2 2 --provides='compiler'
addpkg intel 15.0.6 1 --provides='compiler'
addpkg hdf5-intel 1.8.11 1 --requires='intel' --provides='hdf5; libhdf5.so.7'
addpkg hdf5-intel 1.8.14 1 --requires='intel >= 14.0.1; intel < 15' \
    --provides='hdf5; libhdf5.so.8'

diff - <(./sod -r $repo load intel) <<____
echo loading intel/16.0.2-1.x86_64@test
__sod_set EMAIL 'user@host'
__sod_push PATH '/x/y/z/bin'
__sod_set XYZ '/lib:/x/y/z/lib64'
__sod_push __sod_installed 'intel/16.0.2-1.x86_64@test'
____

diff - <(./sod -r $repo load hdf5-intel) <<____
echo loading intel/14.0.4-1.x86_64@test
__sod_push __sod_installed 'intel/14.0.4-1.x86_64@test'
echo loading hdf5-intel/1.8.14-1.x86_64@test
__sod_push __sod_installed 'hdf5-intel/1.8.14-1.x86_64@test'
____

diff - <(./sod -r $repo -I intel/16.0.2-1.x86_64@test load intel) <<____
____

diff - <(./sod -r $repo -I intel/16.0.2-1.x86_64@test list intel) <<____
echo intel/16.0.2-1.x86_64
____

diff - <(./sod -r $repo -I intel/16.0.2-1.x86_64@test unload intel) <<____
echo unloading intel/16.0.2-1.x86_64@test
__sod_unset XYZ '/lib:/x/y/z/lib64'
__sod_pop PATH '/x/y/z/bin'
__sod_unset EMAIL 'user@host'
__sod_pop __sod_installed 'intel/16.0.2-1.x86_64@test'
____

set +E
diff - <(./sod -r $repo -I intel/16.0.2-1.x86_64@test install intel/15.0.2 2>&1) <<____
sod: intel/16.0.2-1.x86_64@installed is already installed
____
set -E

diff - <(./sod -r $repo -I intel/16.0.2-1.x86_64@test purge | grep unload) <<____
echo unloading intel/16.0.2-1.x86_64@test
____

diff - <(./sod -r $repo -I intel/16.0.2-1.x86_64@test load hdf5-intel) <<____
echo loading hdf5-intel/1.8.11-1.x86_64@test
__sod_push __sod_installed 'hdf5-intel/1.8.11-1.x86_64@test'
____

diff - <(./sod -r $repo load libhdf5.so.7 | grep loading) <<____
echo loading intel/16.0.2-1.x86_64@test
echo loading hdf5-intel/1.8.11-1.x86_64@test
____
diff - <(./sod -r $repo load libhdf5.so.8 | grep loading) <<____
echo loading intel/14.0.4-1.x86_64@test
echo loading hdf5-intel/1.8.14-1.x86_64@test
____

addpkg gcc 5.2.0 1 --provides='compiler'
addpkg hdf5-gcc 1.8.11 1 --requires='gcc' --provides='hdf5; libhdf5.so.7'

diff - <(./sod -r $repo -I 'hdf5-intel/1.8.11-1.x86_64@test:intel/16.0.2-1.x86_64@test' swap hdf5-gcc | grep load) <<____
echo unloading hdf5-intel/1.8.11-1.x86_64@test
echo unloading intel/16.0.2-1.x86_64@test
echo loading gcc/5.2.0-1.x86_64@test
echo loading hdf5-gcc/1.8.11-1.x86_64@test
____

diff - <(./sod -r $repo search summary) <<____
echo intel/16.0.2-1.x86_64
____

echo OK
exit 0
