#!/bin/bash
set -e -u -E
printf "$0: "
trap 'echo error at line $LINENO' ERR

repo=test.sodrepo
[[ -f $repo ]] && rm $repo
unset ${!__sod_*}

./sodrepo -r $repo create
./sodrepo -r $repo add intel 16.0.2 1 x86_64 "summary" <<____
+ PATH /a/b/c
= XYZ /x/y/z
____

function addpkg() {
    ./sodrepo -r $repo add "$@" x86_64 '' <<<''
}
addpkg intel 13.1.1 1
addpkg intel 14.0.4 1
addpkg intel 15.0.2 1
addpkg intel 15.0.2 2
addpkg intel 15.0.6 1
addpkg hdf5-intel 1.8.11 1 --requires='intel' --provides='libhdf5.so.7'
addpkg hdf5-intel 1.8.14 1 --requires='intel >= 14.0.1; intel < 15' \
    --provides='libhdf5.so.8'

cmp <(./sod -r $repo load intel) <<____
echo loading intel-16.0.2-1.x86_64@test
__sod_push PATH '/a/b/c'
__sod_set XYZ '/x/y/z'
__sod_push __sod_installed 'intel-16.0.2-1.x86_64@test'
____

cmp <(./sod -r $repo load hdf5-intel) <<____
echo loading intel-14.0.4-1.x86_64@test
__sod_push __sod_installed 'intel-14.0.4-1.x86_64@test'
echo loading hdf5-intel-1.8.14-1.x86_64@test
__sod_push __sod_installed 'hdf5-intel-1.8.14-1.x86_64@test'
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test load intel) <<____
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test list intel) <<____
echo intel-16.0.2-1.x86_64
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test unload intel) <<____
echo unloading intel-16.0.2-1.x86_64@test
__sod_unset XYZ '/x/y/z'
__sod_pop PATH '/a/b/c'
__sod_pop __sod_installed 'intel-16.0.2-1.x86_64@test'
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test purge | grep unload) <<____
echo unloading intel-16.0.2-1.x86_64@test
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test load hdf5-intel) <<____
echo loading hdf5-intel-1.8.11-1.x86_64@test
__sod_push __sod_installed 'hdf5-intel-1.8.11-1.x86_64@test'
____

cmp <(./sod -r test.sodrepo load libhdf5.so.7 | grep loading) <<____
echo loading intel-16.0.2-1.x86_64@test
echo loading hdf5-intel-1.8.11-1.x86_64@test
____
cmp <(./sod -r test.sodrepo load libhdf5.so.8 | grep loading) <<____
echo loading intel-14.0.4-1.x86_64@test
echo loading hdf5-intel-1.8.14-1.x86_64@test
____

echo OK
exit 0
