#!/bin/bash
set -e -u -E
trap 'echo error at line $LINENO' ERR
trap '[[ $? == 0 ]] && echo OK' EXIT

repo=test.sodrepo
[[ -f $repo ]] && rm $repo
unset __sod_repos
unset __sod_installed

./sodrepo -cr $repo add intel 16.0.2 1 x86_64 "summary" <<____
+ PATH /a/b/c
= XYZ /x/y/z
____
./sodrepo -r $repo add intel 13.1.1 1 x86_64 "" <<<""
./sodrepo -r $repo add intel 14.0.4 1 x86_64 "" <<<""
./sodrepo -r $repo add intel 15.0.2 1 x86_64 "" <<<""
./sodrepo -r $repo add intel 15.0.2 2 x86_64 "" <<<""
./sodrepo -r $repo add intel 15.0.6 1 x86_64 "" <<<""
./sodrepo -r $repo add hdf5-intel 1.8.11 1 x86_64 "" \
    --requires='intel' --provides='libhdf5.so.7' <<<""
./sodrepo -r $repo add hdf5-intel 1.8.14 1 x86_64 "" \
    --requires='intel >= 14.0.1; intel < 15' --provides='libhdf5.so.8' <<<""

cmp <(./sod -r $repo -i intel) <<____
echo loading intel-16.0.2-1.x86_64@test
__sod_push PATH '/a/b/c'
__sod_set XYZ '/x/y/z'
__sod_push __sod_installed 'intel-16.0.2-1.x86_64@test'
____

cmp <(./sod -r $repo -i hdf5-intel) <<____
echo loading intel-14.0.4-1.x86_64@test
__sod_push __sod_installed 'intel-14.0.4-1.x86_64@test'
echo loading hdf5-intel-1.8.14-1.x86_64@test
__sod_push __sod_installed 'hdf5-intel-1.8.14-1.x86_64@test'
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test -i intel) <<____
____

cmp <(./sod -r $repo -I intel-16.0.2-1.x86_64@test -i hdf5-intel) <<____
echo loading hdf5-intel-1.8.11-1.x86_64@test
__sod_push __sod_installed 'hdf5-intel-1.8.11-1.x86_64@test'
____

cmp <(./sod -r test.sodrepo -i libhdf5.so.7 | grep loading) <<____
echo loading intel-16.0.2-1.x86_64@test
echo loading hdf5-intel-1.8.11-1.x86_64@test
____
cmp <(./sod -r test.sodrepo -i libhdf5.so.8 | grep loading) <<____
echo loading intel-14.0.4-1.x86_64@test
echo loading hdf5-intel-1.8.14-1.x86_64@test
____

exit 0
